import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react"
import "./globals.css";
import SwitchTheme from "@/components/switch-theme";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Mandala",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakartaSans.className} antialiased`}
      >
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            {children}
            <SwitchTheme />
            <p className="absolute bottom-2 right-2 dark:text-white *:text-black">Made with luv by 1708238</p>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
