import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import SwitchTheme from "@/components/switch-theme";
import Providers from "@/components/providers";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Mandala",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakartaSans.className} antialiased`}
      >
        <Providers>
          {children}
          <SwitchTheme />
          <p className="fixed bottom-2 right-2 text-muted-foreground">Made with luv by 1708238</p>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
