import type { Metadata } from "next"
import { Plus_Jakarta_Sans } from "next/font/google"
import "./globals.css"
import Providers from "@/components/providers"

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Mandala",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakartaSans.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
